title: Md. Toyeb
description: Computer Science and Engineering, BRAC University
baseurl: "/Resume/"
url: ""
resume_url: "Resume.pdf"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
